namespace Assets.Scrypts
{
    public enum MessageType
    {
        CONNECTION_REQUEST,
        CONNECTION_ACCEPTED,
        USER_ADDED,
        USER_REMOVED,
        TEXT,
        TEST_WORK,
        AUTHORIZATION,
        NULL,
        REGISTRATION,
        ERROR,
        ERROR_AUTHORIZATION,
        ERROR_REGISTRATION,
        GAME,
        LOADING_GAME,
        SET_INFO,
        SET_CHEST,
        SET_ENEMY,
        SET_CARD_START,
        SET_CARD,
        SET_END,
        W,
        A,
        S,
        D,
        DOWN_E,
        UP_E,
        STEP,
        GOT_CHEST,
        GOT_ENEMY,
        READY,
        START,
        ROUND_END
    }
}
